### ISSUE TITLE
rails 5.1

### ISSUE THREAD

**Issue by yoasyo25** [yoasyo25/overtime-app#11]
Rails 5 deprecates `redirect_to :back` method and instead requires a fallback_location to be given to
the redirect_back method. 

Took of ` rescue_from ActionController::RedirectBackError, with: :redirect_to_default`  
https://blog.bigbinary.com/2016/02/29/rails-5-improves-redirect_to_back-with-redirect-back.html

**Comment by yoasyo25** [comment]
```
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /Users/Yohanan/Desktop/NextRequest/nextrequest/config/initializers/new_framework_defaults.rb:23)
```
Removed `# ActiveSupport.halt_callback_chains_on_return_false = false` from new_framework_defaults.rb

**Comment by yoasyo25** [comment]
```
DEPRECATION WARNING: The behavior of `previous_changes` inside of after callbacks is
deprecated without replacement. In the next release of Rails,
this method inside of `after_save` will return the changes that
were just saved.
 (called from create_pretty_id_group at /Users/Yohanan/Desktop/NextRequest/nextrequest/app/models/account.rb:274)
```

```
DEPRECATION WARNING: The behavior of `previous_changes` inside of after callbacks is
deprecated without replacement. In the next release of Rails,
this method inside of `after_save` will return the changes that
were just saved.
 (called from add_nextrequest_admin at /Users/Yohanan/Desktop/NextRequest/nextrequest/app/models/account.rb:261)
```

Underrated and enhanced dirty attributes changes in Rails 5.1
https://www.levups.com/en/blog/2017/undocumented-dirty-attributes-activerecord-changes-rails51.html

**Comment by yoasyo25** [comment]
```
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will 
be changing in the next version of Rails. The new return value will reflect the behavior of calling
 the method after `save` returned (e.g. the opposite of what it returns now). To maintain the 
current behavior, use `saved_change_to_attribute?` instead. (called from reset_undeliverable_if_email_changed at /Users/Yohanan/Desktop/NextRequest/nextrequest/app/models/user.rb:440)
```

<img width="678" alt="screen shot 2018-04-26 at 12 17 28 pm" src="https://user-images.githubusercontent.com/16178096/39318449-2504b182-494c-11e8-9f17-6f2f75c8fb8a.png">


The behavior of `attribute_changed?` inside of after callbacks will be changing
https://github.com/rails/rails/issues/29035
https://github.com/rails/rails/pull/25337#issuecomment-225166796
http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Dirty.html#method-i-will_save_change_to_attribute-3F

**Comment by yoasyo25** [comment]
```
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from add_preference at /Users/Yohanan/Desktop/NextRequest/nextrequest/app/models/user.rb:410)
```

`attribute_changed?` is not called in the application and this warning is being fired incorrectly. The issue is fixed in Rails 5.1-stable.

https://github.com/rails/rails/pull/28640

**Comment by yoasyo25** [comment]
```
ReviewBatchDeleter returns the deleted batches
Failure/Error: return unless @batches.is_a?(ReviewBatch::ActiveRecord_Relation)

NameError:
  private constant #<Class:0x00000000087a7a08>::ActiveRecord_Relation referenced
# ./app/models/review_batch_deleter.rb:7:in `delete'
# ./spec/models/review_batch_deleter_spec.rb:33:in `block (2 levels) in <top (required)>'

ReviewBatchDeleter marks all specified cancelled batches as deleted
Failure/Error: return unless @batches.is_a?(ReviewBatch::ActiveRecord_Relation)

NameError:
  private constant #<Class:0x00000000087a7a08>::ActiveRecord_Relation referenced
# ./app/models/review_batch_deleter.rb:7:in `delete'
# ./spec/models/review_batch_deleter_spec.rb:26:in `block (2 levels) in <top (required)>'
```
Changed `return unless @batches.is_a?(ReviewBatch::ActiveRecord_Relation)` to `return unless @batches.is_a?(ActiveRecord::Relation)`. 

See git issue below for more info 
```
something.is_a?(ActiveRecord::Relation) is fine since ActiveRecord::Relation is part of the public API. something.is_a?(Country::ActiveRecord_Relation) is not fine because the fact that the Country::ActiveRecord_Relation exists is an implementation detail and not part of the public API. 
```

Model ActiveRecord Relation Set as private constant
https://github.com/rails/rails/issues/30943

**Comment by yoasyo25** [comment]
Can't verify CSRF token authenticity 

https://stackoverflow.com/questions/35181340/rails-cant-verify-csrf-token-authenticity-when-making-a-post-request?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by yoasyo25** [comment]
```
 ActiveRecord::HasManyThroughOrderError:
       Cannot have a has_many :through association 'Note#message_templates' which goes through 'Note#notes_message_templates' before the through association is defined.
```

Added 
```
belongs_to :message_template
belongs_to :note
``` 
in notes_message_template.rb
and 
```
  has_many :notes_message_templates
  has_many :notes, through: :notes_message_templates
```
in message_template.rb
has_many: :through 
http://guides.rubyonrails.org/association_basics.html#the-has-many-association

**Comment by yoasyo25** [comment]
DEPRECATION WARNING on line 78 of /Users/Yohanan/.rvm/gems/ruby-2.4.2/gems/foundation-rails-5.5.3.2/vendor/assets/stylesheets/foundation/components/_top-bar.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{lower-bound($medium-range)}")
